filebeat.config.modules.path: /etc/filebeat/modules.d/*.yml

#filebeat.inputs:
#  - type: log
#    paths:
#      - /home/teetotaller/logger.log

#processors:
#  - add_host_metadata:
#      when.not.contains.tags: forwarded
#  - decode_json_fields:
#      fields: ["message"]
#      target: "json"
#      overwrite_keys: true

output.elasticsearch:
  hosts: ["localhost:9200"]

#logging.json: true
logging.metrics.enabled: false
